# Publish workflow: packs and publishes to NuGet on push to master

name: Publish

on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack src/MATTAR.OCR.csproj --configuration Release --no-build --output ./nupkgs
    - name: Publish to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
